# Generated by Django 5.2.5 on 2026-01-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_credits', models.BooleanField(default=True, verbose_name='Habilitar Fiados')),
                ('enable_categories', models.BooleanField(default=True, verbose_name='Habilitar Categorías')),
                ('enable_expiration_alerts', models.BooleanField(default=True, verbose_name='Habilitar Alertas de Vencimiento')),
                ('enable_low_stock_alerts', models.BooleanField(default=True, verbose_name='Habilitar Alertas de Stock Bajo')),
                ('enable_barcode_scanner', models.BooleanField(default=True, verbose_name='Habilitar Escáner de Códigos')),
                ('enable_reports', models.BooleanField(default=True, verbose_name='Habilitar Reportes')),
                ('enable_customers', models.BooleanField(default=True, verbose_name='Habilitar Gestión de Clientes')),
                ('company_name', models.CharField(default='StockMaster', max_length=200, verbose_name='Nombre del negocio')),
                ('expiration_alert_days', models.IntegerField(default=30, verbose_name='Días de alerta de vencimiento')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
    ]
