# Generated by Django 5.2.5 on 2026-01-27 16:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('low_stock_count', models.IntegerField(default=0)),
                ('expiring_soon_count', models.IntegerField(default=0)),
                ('expired_count', models.IntegerField(default=0)),
                ('high_debt_count', models.IntegerField(default=0)),
                ('low_stock_ids', models.TextField(blank=True, default='')),
                ('expiring_soon_ids', models.TextField(blank=True, default='')),
                ('expired_ids', models.TextField(blank=True, default='')),
                ('high_debt_ids', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
    ]
