# Generated by Django 5.2.5 on 2026-01-27 23:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_return_returnitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada')], default='OPEN', max_length=10)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opening_amount', models.DecimalField(decimal_places=2, default=0, help_text='Efectivo inicial en caja', max_digits=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closing_amount', models.DecimalField(decimal_places=2, default=0, help_text='Efectivo real contado al cerrar', max_digits=10)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, help_text='Efectivo esperado según ventas', max_digits=10)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_transfer_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_credit_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('difference', models.DecimalField(decimal_places=2, default=0, help_text='Diferencia entre real y esperado', max_digits=10)),
                ('opening_notes', models.TextField(blank=True, default='')),
                ('closing_notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_registers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Egreso')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(help_text='Motivo del movimiento', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='sales.cashregister')),
            ],
            options={
                'verbose_name': 'Movimiento de Efectivo',
                'verbose_name_plural': 'Movimientos de Efectivo',
                'ordering': ['-created_at'],
            },
        ),
    ]
