# Generated by Django 5.2.5 on 2026-01-31 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company'),
        ('sales', '0004_cashregister_cashmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='closing_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='expected_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='opening_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('company', 'name')},
        ),
    ]
